//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaCenter.Models.Entity
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;

	public partial class MediaCenterEntities : DbContext
	{
		private static MediaCenterEntities _ctx;

		public static MediaCenterEntities GetContext()
		{
			if (_ctx == null)
				_ctx = new MediaCenterEntities();
			return _ctx;
		}
		public MediaCenterEntities()
						: base("name=MediaCenterEntities")
		{
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			throw new UnintentionalCodeFirstException();
		}

		public virtual DbSet<Customer> Customers { get; set; }
		public virtual DbSet<Document> Documents { get; set; }
		public virtual DbSet<Manager> Managers { get; set; }
		public virtual DbSet<Order> Orders { get; set; }
		public virtual DbSet<Service> Services { get; set; }
		public virtual DbSet<Setting> Settings { get; set; }
		public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
		public virtual DbSet<TypeService> TypeServices { get; set; }
		public virtual DbSet<User> Users { get; set; }
	}
}
