//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaCenter.Models.Entity
{
	using System;
	using System.Collections.Generic;

	public partial class Manager
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Manager()
		{
			this.Orders = new HashSet<Order>();
		}

		public int ID { get; set; }
		public string Surname { get; set; }
		public string Name { get; set; }
		public string Patronymic { get; set; }
		public string Fullname => $"{Surname} {Name} {Patronymic}";
		public string Phone { get; set; }
		public string Email { get; set; }
		public Nullable<int> IDUser { get; set; }
		public byte[] Image { get; set; }

		public virtual User User { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Order> Orders { get; set; }
	}
}
