//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaCenter.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int IDCustomer { get; set; }
        public int IDManager { get; set; }
        public int IDService { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public byte[] Sound { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Service Service { get; set; }
    }
}
